
include:
  - java-one/docker-compose.yaml
  - java-two/docker-compose.yaml

services:
  forward:
    profiles:
      - runForward
    image: forward:latest
    build:
      context: tcp-forwarder
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forward-two.rule=PathPrefix(`/api/two`)"
      - "traefik.http.routers.forward-two.entrypoints=web"
      - "traefik.http.services.forward-two.loadbalancer.server.port=80"
#      - "traefik.http.services.app-two.loadbalancer.server.scheme=https" # Use HTTPS for upstream
      - "traefik.http.services.forward-two.loadbalancer.sticky.cookie=false"
    environment:
      - TARGET_HOST=traefik-lb
      - TARGET_PORT=8080

  gateway:
    image: traefik-custom:v2.11
    build:
      context: dockerbuild
    command:
      - --providers.file.filename=/traefik_conf.yml
      - --entrypoints.web.address=:80
#      - --entrypoints.web.http.redirections.entryPoint.to=websecure
#      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      - --api
      - --api.insecure=true
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default
  standby:
    image: traefik-custom:v2.11
    command:
      - --providers.file.filename=/traefik_conf.yml
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      - --api
      - --api.insecure=true
      - --api.dashboard=true
    ports:
      - "81:80"
      - "444:443"
      - "8889:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default
  web:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`example.localhost.direct`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.services.web.loadbalancer.server.port=443"
      - "traefik.http.services.web.loadbalancer.server.scheme=https" # Use HTTPS for upstream
      - "traefik.http.services.web.loadbalancer.sticky.cookie=false"

    networks:
      - internal
    deploy:
      replicas: 2

networks:
  internal:
    driver: bridge

  default:
    name: docker-default-network
    external: true
