networks:
  default:
    name: docker-default-network
    external: true
  backend:

services:
  postgres-one:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greetingdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app-one:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres-one:
        condition: service_healthy
      app-two:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/greetingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    links:
      - "postgres-one:postgres"
