networks:
  default:
    name: docker-default-network
    external: true
  internal:
    driver: bridge
  proxy:

services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
    networks:
      - proxy

  gateway:
    image: traefik-custom:v2.11
    build:
      context: .
    command:
      - --providers.file.filename=/traefik_conf.yml
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --entrypoints.web.address=:80
      #      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      #      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      - --api
      - --api.insecure=true
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    networks:
      - internal
      - default
      - proxy

  standby:
    image: traefik-custom:v2.11
    command:
      - --providers.file.filename=/traefik_conf.yml
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      - --api
      - --api.insecure=true
      - --api.dashboard=true
    ports:
      - "81:80"
      - "444:443"
      - "8889:8080"
    networks:
      - internal
      - default
      - proxy
  web:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`example.localhost.direct`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.services.web.loadbalancer.server.port=443"
      - "traefik.http.services.web.loadbalancer.server.scheme=https" # Use HTTPS for upstream
      - "traefik.http.services.web.loadbalancer.sticky.cookie=false"
    networks:
      - internal
    deploy:
      replicas: 2
