networks:
  default:
    name: docker-default-network
    external: true
  backends:
  edge:
  dockerd:

services:
  dockerd-proxy:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LOG_LEVEL: "notice"
      CONTAINERS: 1
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "2375"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 1s
    networks:
      - dockerd

  gateway:
    image: traefik-custom:v2.11
    build:
      context: .
    command:
      - --providers.file.filename=/traefik_conf.yml
      - --providers.docker.endpoint=tcp://dockerd-proxy:2375
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      - --api
      - --api.insecure=true
      - --api.dashboard=true
    depends_on:
      dockerd-proxy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "443"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 1s
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    networks:
      - backends
      - edge
      - default
      - dockerd

  standby:
    image: traefik-custom:v2.11
    command:
      - --providers.file.filename=/traefik_conf.yml
      - --providers.docker.endpoint=tcp://dockerd-proxy:2375
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      - --api
      - --api.insecure=true
      - --api.dashboard=true
    depends_on:
      dockerd-proxy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "443"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 1s
    ports:
      - "81:80"
      - "444:443"
      - "8889:8080"
    networks:
      - backends
      - edge
      - default
      - dockerd

