networks:
  default:
    name: docker-default-network
    external: true

services:
  postgres-three:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app-three-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 3

  app-three:
    image: app-three.jvm
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres-three:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost/q/health"]
      interval: 1s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-three.rule=PathPrefix(`/api/three`)"
      - "traefik.http.routers.app-three.entrypoints=web,websecure"
      - "traefik.http.services.app-three.loadbalancer.server.port=443"
      - "traefik.http.services.app-three.loadbalancer.server.scheme=https"
      - "traefik.http.services.app-three.loadbalancer.healthcheck.path=/q/health"
      - "traefik.http.services.app-three.loadbalancer.healthcheck.port=443"

  app-three-native:
    image: app-three.native
    build:
      context: .
      dockerfile: Dockerfile.native
    depends_on:
      postgres-three:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost/q/health"]
      interval: 2s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-three-native.rule=PathPrefix(`/api/three`)"
      - "traefik.http.routers.app-three-native.entrypoints=web,websecure"
      - "traefik.http.services.app-three-native.loadbalancer.server.port=443"
      - "traefik.http.services.app-three-native.loadbalancer.server.scheme=https"
      - "traefik.http.services.app-three-native.loadbalancer.healthcheck.path=/q/health"
      - "traefik.http.services.app-three-native.loadbalancer.healthcheck.port=443"

volumes:
  postgres_data:
