networks:
  default:
    name: docker-default-network
    external: true

  backend:

services:
  postgres-two:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app-two-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 3

  app-two:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres-two:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-two.rule=PathPrefix(`/api/two`)"
      - "traefik.http.routers.app-two.entrypoints=web,websecure"
      - "traefik.http.services.app-two.loadbalancer.server.port=8080"
#      - "traefik.http.services.app-two.loadbalancer.server.scheme=https" # Use HTTPS for upstream
      - "traefik.http.services.app-two.loadbalancer.sticky.cookie=false"



volumes:
  postgres_data:
